# Generated by Django 4.2.7 on 2025-05-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Adoption Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason_for_adoption', models.TextField(help_text='Why do you want to adopt this pet?')),
                ('experience_with_pets', models.TextField(help_text='Describe your experience with pets')),
                ('living_situation', models.TextField(help_text='Describe your living situation')),
                ('work_schedule', models.TextField(help_text='Describe your work schedule and how it affects pet care')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('veterinarian_name', models.CharField(blank=True, max_length=100)),
                ('veterinarian_phone', models.CharField(blank=True, max_length=15)),
                ('veterinarian_address', models.TextField(blank=True)),
                ('additional_notes', models.TextField(blank=True, help_text="Any additional information you'd like to share")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True, help_text='Notes from the shelter reviewer')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Adoption Contract'), ('medical_records', 'Medical Records'), ('vaccination_records', 'Vaccination Records'), ('identification', 'ID Document'), ('proof_of_residence', 'Proof of Residence'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='adoption_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Interview'), ('video', 'Video Call'), ('in_person', 'In-Person Meeting'), ('home_visit', 'Home Visit')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='adoptions.adoptionapplication')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
