# Generated by Django 4.2.7 on 2025-05-31 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adoptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptioninterview',
            name='interviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptiondocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='adoptions.adoptionapplication'),
        ),
        migrations.AddField(
            model_name='adoptiondocument',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adoptionapplication',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_applications', to='pets.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='adoptionapplication',
            unique_together={('applicant', 'pet')},
        ),
    ]
