# Generated by Django 4.2.7 on 2025-05-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('guinea_pig', 'Guinea Pig'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('age_years', models.PositiveIntegerField(default=0)),
                ('age_months', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=10)),
                ('size', models.CharField(choices=[('small', 'Small (0-25 lbs)'), ('medium', 'Medium (26-60 lbs)'), ('large', 'Large (61-100 lbs)'), ('extra_large', 'Extra Large (100+ lbs)')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in pounds', max_digits=5)),
                ('color', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending Adoption'), ('adopted', 'Adopted'), ('not_available', 'Not Available')], default='available', max_length=20)),
                ('description', models.TextField()),
                ('personality_traits', models.TextField(blank=True, help_text='Friendly, energetic, calm, etc.')),
                ('good_with_kids', models.BooleanField(default=False)),
                ('good_with_dogs', models.BooleanField(default=False)),
                ('good_with_cats', models.BooleanField(default=False)),
                ('house_trained', models.BooleanField(default=False)),
                ('is_spayed_neutered', models.BooleanField(default=False)),
                ('is_vaccinated', models.BooleanField(default=False)),
                ('medical_notes', models.TextField(blank=True)),
                ('special_needs', models.TextField(blank=True)),
                ('adoption_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pets.pet')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PetFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='pets.pet')),
            ],
        ),
    ]
